name: Test Check
on:
  pull_request:
    branches: [ dev ] # or master, depending on your default branch

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensures history is available for comparison

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - run: bun install --ignore-scripts

      - name: Build workspace
        run: bun run build


        
